baseURL = "https://hubbardton.org/"
languageCode = "en-us"
title = "Hubbardton Historical Society"
theme = "hubbardton-org"
newContentEditor = "nvim"
mainSections = ["default"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "-"
  siteHeading = "Hubbardton Historical Society" # defaults to author
  favicon = "logo_64.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["default"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "Hubbardton History"

  [params.social]
    facebook = "HubbardtonHistoricalSociety"
    email = "history@hubbardton.net"
    phone = "802-273-3901"

[taxonomies]
  year = "year"
  #month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  history = "/history/:slug"
